### ISSUE TITLE
Issue with defend_the_center.cfg

### ISSUE THREAD

**Issue by Shmuma** [flyyufelix/C51-DDQN-Keras#2]
Latest version of ViZDoom have this line in **scenarios/defend_the_center.cfg**
`
available_game_variables = { AMMO2 HEALTH  }
`

But your code expects to have three variables, so this line need to be changed to this
`
available_game_variables = { KILLCOUNT AMMO2 HEALTH  }
`

It's not a big deal, but should be reflected in the README, I think.

Additionally, the training process crashes without **statistics** dir created beforehead.

**Comment by flyyufelix** [comment]
Oh, thanks for reminding! I forgot I've even made this change in the config. Let me add to README. 

Update: README is edited
