### ISSUE TITLE
IndexError: index 2 is out of bounds for axis 0 with size 2

### ISSUE THREAD

**Issue by forhonourlx** [flyyufelix/C51-DDQN-Keras#3]
Traceback (most recent call last):
File "c51_ddqn.py", line 290, in 
r_t = agent.shape_reward(r_t, misc, prev_misc, t)
File "c51_ddqn.py", line 123, in shape_reward
if (misc[2] < prev_misc[2]): # Loss HEALTH
IndexError: index 2 is out of bounds for axis 0 with size 2

Could someone kindly help me?
Thanks.

**Comment by forhonourlx** [comment]
with ViZDoom-1.1.5pre-Win-Python35-x86_64

**Comment by flyyufelix** [comment]
Please refer to this https://github.com/flyyufelix/C51-DDQN-Keras/issues/2. And also see README for instruction to edit the config file

**Comment by forhonourlx** [comment]
Thanks. It does work.
