### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'statistics/c51_ddqn_stats.txt'

### ISSUE THREAD

**Issue by forhonourlx** [flyyufelix/C51-DDQN-Keras#4]
Update Rolling Statistics
Traceback (most recent call last):
  File "c51_ddqn.py", line 341, in <module>
    with open("statistics/c51_ddqn_stats.txt", "w") as stats_file:
FileNotFoundError: [Errno 2] No such file or directory: 'statistics/c51_ddqn_stats.txt'

**Comment by flyyufelix** [comment]
You have to create a `statistics` directory to store the statistics file. 

```
cd examples/python
mkdir statistics
```
